[build]
  command = """
    mkdir -p ~/.local/bin
    wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.tar.gz
    tar -xzf quarto-1.3.450-linux-amd64.tar.gz -C ~/.local
    export PATH=$PATH:~/.local/quarto-1.3.450/bin
    quarto --version
    quarto render
  """
  publish = "_site"

[build.environment]
  # Set PATH to include Quarto
  PATH = "/.local/quarto-1.3.450/bin:${PATH}"
